Rework of UTemp application. This is a minimalistic, hardcoded version.

diff --git a/bin/archiver b/bin/archiver
--- a/bin/archiver
+++ b/bin/archiver
@@ -1,14 +1,12 @@
 #!/bin/bash
 
-#
-# TODO:
-# SELECT strftime('%Y-%m', stamputc, 'localtime') AS quantum, count(*) FROM temperature WHERE stamputc <= '2017-03-05' GROUP BY quantum;
-
+SQLC="/usr/bin/sqlite3"
+BZIP2="/usr/bin/bzip2"
 
 function help() {
-    echo "archive.sh <options> [day]" >&2
+    echo "$0 <options> [day]" >&2
     echo "  day ... archive check point day" >&2
-    echo "          format od the day is YYYY-MM-DD" >&2
+    echo "          format of the day is YYYY-MM-DD" >&2
     echo "          The default is the last day of the previous month" >&2
     echo "Options:" >&2
     echo "  -c|--current <database>  ... the database with current data" >&2
@@ -18,16 +16,18 @@ function help() {
     echo "                               The default is 'month'" >&2
     echo "  -f|--format <csv|db|sql> ... format of the archive files" >&2
     echo "                               The default is 'sql'" >&2
-    echo "  -r|--remove              ... Remove archived records from the current database" >&2
+    echo "  -r|--remove              ... remove archived records from the current database" >&2
+    echo "  -C|--compress            ... compress the archive" >&2
     exit $1
 }
 
 # Parse command line
-DATABASE=""
+DATABASE="current.db"
 PREFIX="./archive"
 GRANULARITY="month"
 FORMAT="sql"
 REMOVE=""
+COMPRESS=""
 DAY=$(date +'%Y-%m-%d' -d "-$(date +%d) days")
 while [[ $# -ne 0 ]]; do
     case "$1" in
@@ -66,6 +66,9 @@ while [[ $# -ne 0 ]]; do
         "-r"|"--remove")
             REMOVE="1"
             ;;
+        "-C"|"--compress")
+            COMPRESS="1"
+            ;;
         "--help")
             help 0
             ;;
@@ -81,15 +84,15 @@ while [[ $# -ne 0 ]]; do
 done
 
 # Check mandatory parameters
-[[ -z "${DATABASE}" ]] && { echo "Missing mandatory database parameter '-d'" >&2; help 1; }
+[[ -z "${DATABASE}" ]] && { echo "Missing mandatory database parameter '-c'" >&2; help 1; }
 
 
 # Debug info
-echo "Database:" $DATABASE
-echo "Prefix:" $PREFIX
-echo "Granularity:" $GRANULARITY
-echo "Format:" $FORMAT
-echo "Day:" $DAY
+#echo "Database:" $DATABASE
+#echo "Prefix:" $PREFIX
+#echo "Granularity:" $GRANULARITY
+#echo "Format:" $FORMAT
+#echo "Day:" $DAY
 
 #
 # Returns list of time quantas
@@ -119,7 +122,7 @@ function get_time_quantas() {
         FROM temperature
         WHERE stamputc <= datetime('${DAY} 23:59:59', 'localtime')
         GROUP BY stamp
-        ORDER BY stamp;" | sqlite3 "${DATABASE}" && return 0
+        ORDER BY stamp;" | "${SQLC}" "${DATABASE}" && return 0
 
     echo "Unknown error when querying database ${DATABASE}" >&2
     return 1
@@ -186,6 +189,12 @@ function archive_quantum() {
             archive_quantum_csv "${g}" $* || return $?
             ;;
     esac
+    # Compress the file if requested and the file has any content
+    if [[ -s "${1}" ]]; then
+        [[ -n "${COMPRESS}" ]] && "${BZIP2}" "${1}"
+    else
+        rm -f "${1}"
+    fi
     return 0
 }
 
@@ -196,7 +205,7 @@ function archive_quantum_csv() {
         WHERE strftime('${1}', stamputc, 'localtime') = '${3}';"
     [[ -n "${REMOVE}" ]] && \
         echo "DELETE FROM temperature WHERE strftime('${1}', stamputc, 'localtime') = '${3}';"
-    } | sqlite3 "${DATABASE}" >> "${2}"
+    } | "${SQLC}" "${DATABASE}" >> "${2}"
 
     return $?
 }
@@ -208,7 +217,7 @@ function archive_quantum_sql() {
         WHERE strftime('${1}', stamputc, 'localtime') = '${3}';"
     [[ -n "${REMOVE}" ]] && \
         echo "DELETE FROM temperature WHERE strftime('${1}', stamputc, 'localtime') = '${3}';"
-    } | sqlite3 "${DATABASE}" >> "${2}"
+    } | "${SQLC}" "${DATABASE}" >> "${2}"
 
     return $?
 }
@@ -231,7 +240,7 @@ function archive_quantum_db() {
         echo "DELETE FROM db.temperature WHERE strftime('${1}', stamputc, 'localtime') = '${3}';"
 
     echo "DETACH db;"
-    } | sqlite3 "${2}"
+    } | "${SQLC}" "${2}"
 
     return $?
 }
diff --git a/bin/measurer b/bin/measurer
--- a/bin/measurer
+++ b/bin/measurer
@@ -2,19 +2,18 @@
 
 W1_BUS='/sys/bus/w1/devices'
 SQLITE="/usr/bin/sqlite3"
-DB=""
+DB="/mnt/utemp/var/current.db"
+LOGGER="/usr/bin/logger"
+LOGTAG="UTEMP:$(basename $0)"
 CREATE=""
 
 function help {
-    echo "Measure tempereture and store it in a database file" >&2
-    echo "" >&2
-    echo "Usage:" >&2
-    echo "$0 [options] <database>" >&2
-    echo "Options:" >&2
-    echo "   -c|--create ... Create the DB if it is not already created" >&2
-    echo "Parameters:" >&2
-    echo "   database    ... the database file to insert the measured values into" >&2
-    exit $1
+        echo "$0 [options] <database>" >&2
+        echo "Options:" >&2
+        echo "   -c|--create ... Create the DB if it is not already created" >&2
+        echo "Parameters:" >&2
+        echo "   database    ... the database file to insert the measured values into" >&2
+        exit $1
 }
 
 function createdb {
@@ -37,6 +36,8 @@ function measure {
     # Exits immediatelly if no sensor is available
     ls ${W1_BUS}/*/w1_slave >& /dev/null || return 1
 
+    log "Starting to measure temperature"
+    i=0
     # Read data from all the available sensors
     for sensor in ${W1_BUS}/*/w1_slave; do
         measurement=$(cat "${sensor}")
@@ -46,7 +47,9 @@ function measure {
             temperature=$(echo "${measurement}"|tail -1|cut -d '=' -f 2)
             echo ${sensor} ${temperature}
         fi
+        i=$(( $i + 1 ))
     done
+    log "Temperature measured for $i sensors"
     return 0
 }
 
@@ -56,6 +59,10 @@ function printsql {
         echo -n $(date -u +'%Y-%m-%d %H:%M:%S')
         echo "',${temperature},'${sensor}');"
     done
+}
+
+function log {
+    echo $* | "${LOGGER}" -t "${LOGTAG}"
 }
 
 # Parse command line
@@ -70,19 +77,19 @@ while [[ $# -ne 0 ]]; do
     shift
 done
 
-[[ -z "${DB}" ]] && { echo "Missing database parametr." >&2; help 1; }
-
 # Create DB if required
 if [[ -n "${CREATE}" ]]; then
+    log "Creating database ${DB}"
     createdb | "${SQLITE}" "${DB}"
     ERR=$?
-    [[ ${ERR} -ne 0 ]] && exit ${ERR}
+    [[ ${ERR} -ne 0 ]] && { log "Creation of database ${DB} has failed"; exit ${ERR}; }
 fi
 
 # Do the measurement and save the results in DB
 printsql | "${SQLITE}" "${DB}"
 ERR=$?
-[[ ${ERR} -ne 0 ]] && exit ${ERR}
+[[ ${ERR} -ne 0 ]] && { log "Save of measured values has failed"; exit ${ERR}; }
+log "Measured values saved into ${DB}"
 
 exit 0
 #EOF
